project:
  type: website

website:
  title: "Tomás Pieroni"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        href: proyectos.qmd
      - text: "Sobre mí"
        href: about.qmd
      - text: "Experiencia"
        href: experiencia.qmd
      - text: "Publicaciones"
        href: publicaciones.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: es
